import type { Job, Company } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getLogo = (seed: string) => PlaceHolderImages.find(img => img.id === seed)?.imageUrl || 'https://picsum.photos/seed/default/100/100';

const companies: Company[] = [
  { id: 'comp-1', name: 'Innovate Solutions', logoUrl: getLogo('logo-1'), industry: 'Technology' },
  { id: 'comp-2', name: 'Quantum Dynamics', logoUrl: getLogo('logo-2'), industry: 'Finance' },
  { id: 'comp-3', name: 'GreenLeaf Organics', logoUrl: getLogo('logo-3'), industry: 'Agriculture' },
  { id: 'comp-4', name: 'Nexus Health', logoUrl: getLogo('logo-4'), industry: 'Healthcare' },
  { id: 'comp-5', name: 'Constructo Corp', logoUrl: getLogo('logo-5'), industry: 'Construction' },
  { id: 'comp-6', name: 'EduVerse', logoUrl: getLogo('logo-6'), industry: 'Education' },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Frontend Developer',
    company: companies[0],
    location: 'Lagos, Nigeria',
    salary: { min: 300000, max: 500000 },
    type: 'Full-time',
    experienceLevel: 'Senior',
    industry: 'Technology',
    description: 'We are looking for a skilled Senior Frontend Developer to join our team. You will be responsible for building the ‘client-side’ of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications.',
    postedAt: new Date('2024-05-20'),
  },
  {
    id: 'job-2',
    title: 'Financial Analyst',
    company: companies[1],
    location: 'Abuja, Nigeria',
    salary: { min: 250000, max: 400000 },
    type: 'Full-time',
    experienceLevel: 'Mid',
    industry: 'Finance',
    description: 'Quantum Dynamics is seeking a Financial Analyst to provide accurate and data-based information on company’s profitability, solvency, stability and liquidity. You will research and analyze financial information to help company make well-informed decisions, write reports and monitor financial movements.',
    postedAt: new Date('2024-05-18'),
  },
  {
    id: 'job-3',
    title: 'Marketing Intern',
    company: companies[2],
    location: 'Port Harcourt, Nigeria',
    salary: { min: 50000, max: 80000 },
    type: 'Internship',
    experienceLevel: 'Entry',
    industry: 'Agriculture',
    description: 'GreenLeaf Organics is offering a Marketing Internship. This is an excellent opportunity for students and recent graduates to gain hands-on experience in a fast-growing industry. You will assist in the creation of signage, mock-ups, email campaigns, and social media content.',
    postedAt: new Date('2024-05-21'),
  },
  {
    id: 'job-4',
    title: 'Registered Nurse',
    company: companies[3],
    location: 'Kano, Nigeria',
    salary: { min: 150000, max: 250000 },
    type: 'Contract',
    experienceLevel: 'Mid',
    industry: 'Healthcare',
    description: 'Nexus Health is hiring a compassionate and skilled Registered Nurse. The ideal candidate will be responsible for providing direct patient care, administering medications, and collaborating with physicians to create a plan of care for patients.',
    postedAt: new Date('2024-05-15'),
  },
  {
    id: 'job-5',
    title: 'Project Manager (Construction)',
    company: companies[4],
    location: 'Lagos, Nigeria',
    salary: { min: 400000, max: 600000 },
    type: 'Full-time',
    experienceLevel: 'Senior',
    industry: 'Construction',
    description: 'Constructo Corp is looking for an experienced Construction Project Manager to plan and supervise a wide range of construction projects from start to finish. You will organize and oversee construction procedures and ensure they are completed in a timely and efficient manner.',
    postedAt: new Date('2024-05-19'),
  },
  {
    id: 'job-6',
    title: 'Lead Backend Engineer',
    company: companies[0],
    location: 'Remote',
    salary: { min: 450000, max: 700000 },
    type: 'Full-time',
    experienceLevel: 'Lead',
    industry: 'Technology',
    description: 'Join Innovate Solutions as a Lead Backend Engineer to guide our server-side development team. You will be responsible for the architecture, design, and implementation of our backend services. Strong experience with Node.js and PostgreSQL is required.',
    postedAt: new Date('2024-05-22'),
  },
  {
    id: 'job-7',
    title: 'Curriculum Developer',
    company: companies[5],
    location: 'Abuja, Nigeria',
    salary: { min: 200000, max: 350000 },
    type: 'Part-time',
    experienceLevel: 'Mid',
    industry: 'Education',
    description: 'EduVerse is seeking a creative Curriculum Developer to design and develop engaging learning materials for our e-learning platform. You will work with subject matter experts to create content that is instructionally sound and visually appealing.',
    postedAt: new Date('2024-05-17'),
  },
];
