import type { Job, Company, Application, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getLogo = (seed: string) => PlaceHolderImages.find(img => img.id === seed)?.imageUrl || 'https://picsum.photos/seed/default/100/100';

const companies: Company[] = [
  { id: 'comp-1', name: 'Innovate Solutions', logoUrl: getLogo('logo-1'), industry: 'Technology' },
  { id: 'comp-2', name: 'Quantum Dynamics', logoUrl: getLogo('logo-2'), industry: 'Finance' },
  { id: 'comp-3', name: 'GreenLeaf Organics', logoUrl: getLogo('logo-3'), industry: 'Agriculture' },
  { id: 'comp-4', name: 'Nexus Health', logoUrl: getLogo('logo-4'), industry: 'Healthcare' },
  { id: 'comp-5', name: 'Constructo Corp', logoUrl: getLogo('logo-5'), industry: 'Construction' },
  { id: 'comp-6', name: 'EduVerse', logoUrl: getLogo('logo-6'), industry: 'Education' },
  { id: 'comp-7', name: 'Aero-Link', logoUrl: getLogo('logo-2'), industry: 'Aviation' },
  { id: 'comp-8', name: 'Media Mingle', logoUrl: getLogo('logo-3'), industry: 'Media' },
  { id: 'comp-9', name: 'Hospitality Hub', logoUrl: getLogo('logo-4'), industry: 'Hospitality' },
  { id: 'comp-10', name: 'Retail Realm', logoUrl: getLogo('logo-5'), industry: 'Retail' },
  { id: 'comp-11', name: 'Energy Inc.', logoUrl: getLogo('logo-6'), industry: 'Energy' },
];

const mockUser: User = {
    id: 'user-1',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    role: 'Job Seeker',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'user-avatar-1')?.imageUrl
};

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Frontend Developer',
    company: companies[0],
    location: 'Lagos, Nigeria',
    salary: { min: 300000, max: 500000 },
    type: 'Full-time',
    experienceLevel: 'Senior',
    industry: 'Technology',
    description: 'We are looking for a skilled Senior Frontend Developer to join our team. You will be responsible for building the ‘client-side’ of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications.',
    postedAt: new Date('2024-05-20'),
  },
  {
    id: 'job-2',
    title: 'Financial Analyst',
    company: companies[1],
    location: 'Abuja, Nigeria',
    salary: { min: 250000, max: 400000 },
    type: 'Full-time',
    experienceLevel: 'Mid',
    industry: 'Finance',
    description: 'Quantum Dynamics is seeking a Financial Analyst to provide accurate and data-based information on company’s profitability, solvency, stability and liquidity. You will research and analyze financial information to help company make well-informed decisions, write reports and monitor financial movements.',
    postedAt: new Date('2024-05-18'),
  },
  {
    id: 'job-3',
    title: 'Marketing Intern',
    company: companies[2],
    location: 'Port Harcourt, Nigeria',
    salary: { min: 50000, max: 80000 },
    type: 'Internship',
    experienceLevel: 'Entry',
    industry: 'Agriculture',
    description: 'GreenLeaf Organics is offering a Marketing Internship. This is an excellent opportunity for students and recent graduates to gain hands-on experience in a fast-growing industry. You will assist in the creation of signage, mock-ups, email campaigns, and social media content.',
    postedAt: new Date('2024-05-21'),
  },
  {
    id: 'job-4',
    title: 'Registered Nurse',
    company: companies[3],
    location: 'Kano, Nigeria',
    salary: { min: 150000, max: 250000 },
    type: 'Contract',
    experienceLevel: 'Mid',
    industry: 'Healthcare',
    description: 'Nexus Health is hiring a compassionate and skilled Registered Nurse. The ideal candidate will be responsible for providing direct patient care, administering medications, and collaborating with physicians to create a plan of care for patients.',
    postedAt: new Date('2024-05-15'),
  },
  {
    id: 'job-5',
    title: 'Project Manager (Construction)',
    company: companies[4],
    location: 'Lagos, Nigeria',
    salary: { min: 400000, max: 600000 },
    type: 'Full-time',
    experienceLevel: 'Senior',
    industry: 'Construction',
    description: 'Constructo Corp is looking for an experienced Construction Project Manager to plan and supervise a wide range of construction projects from start to finish. You will organize and oversee construction procedures and ensure they are completed in a timely and efficient manner.',
    postedAt: new Date('2024-05-19'),
  },
  {
    id: 'job-6',
    title: 'Lead Backend Engineer',
    company: companies[0],
    location: 'Remote',
    salary: { min: 450000, max: 700000 },
    type: 'Full-time',
    experienceLevel: 'Lead',
    industry: 'Technology',
    description: 'Join Innovate Solutions as a Lead Backend Engineer to guide our server-side development team. You will be responsible for the architecture, design, and implementation of our backend services. Strong experience with Node.js and PostgreSQL is required.',
    postedAt: new Date('2024-05-22'),
  },
  {
    id: 'job-7',
    title: 'Curriculum Developer',
    company: companies[5],
    location: 'Abuja, Nigeria',
    salary: { min: 200000, max: 350000 },
    type: 'Part-time',
    experienceLevel: 'Mid',
    industry: 'Education',
    description: 'EduVerse is seeking a creative Curriculum Developer to design and develop engaging learning materials for our e-learning platform. You will work with subject matter experts to create content that is instructionally sound and visually appealing.',
    postedAt: new Date('2024-05-17'),
  },
    {
    id: 'job-8',
    title: 'Airline Pilot',
    company: companies[6],
    location: 'Lagos, Nigeria',
    salary: { min: 800000, max: 1200000 },
    type: 'Full-time',
    experienceLevel: 'Senior',
    industry: 'Aviation',
    description: 'Aero-Link is looking for experienced Airline Pilots to join our fleet. Candidates must have a valid commercial pilot license and a minimum of 3,000 flying hours. Safety and professionalism are our top priorities.',
    postedAt: new Date('2024-05-23'),
  },
  {
    id: 'job-9',
    title: 'Social Media Manager',
    company: companies[7],
    location: 'Remote',
    salary: { min: 150000, max: 250000 },
    type: 'Full-time',
    experienceLevel: 'Mid',
    industry: 'Media',
    description: 'Media Mingle is seeking a creative and strategic Social Media Manager to grow our online presence. You will be responsible for developing and implementing our social media strategy across various platforms.',
    postedAt: new Date('2024-05-24'),
  },
  {
    id: 'job-10',
    title: 'Hotel Manager',
    company: companies[8],
    location: 'Abuja, Nigeria',
    salary: { min: 300000, max: 500000 },
    type: 'Full-time',
    experienceLevel: 'Senior',
    industry: 'Hospitality',
    description: 'Hospitality Hub is hiring an experienced Hotel Manager to oversee the daily operations of our luxury hotel. You will be responsible for managing staff, budgets, and ensuring our guests have an exceptional experience.',
    postedAt: new Date('2024-05-25'),
  },
  {
    id: 'job-11',
    title: 'Retail Store Manager',
    company: companies[9],
    location: 'Kano, Nigeria',
    salary: { min: 120000, max: 200000 },
    type: 'Full-time',
    experienceLevel: 'Mid',
    industry: 'Retail',
    description: 'Retail Realm is looking for a results-driven Retail Store Manager to be responsible for the overall store management. The successful candidate will be able to enhance customer satisfaction, meet sales and profitability goals and manage staff effectively.',
    postedAt: new Date('2024-05-25'),
  },
  {
    id: 'job-12',
    title: 'Solar Energy Technician',
    company: companies[10],
    location: 'Kaduna, Nigeria',
    salary: { min: 180000, max: 300000 },
    type: 'Full-time',
    experienceLevel: 'Mid',
    industry: 'Energy',
    description: 'Energy Inc. is seeking a skilled Solar Energy Technician to assemble, install, and maintain solar photovoltaic (PV) systems on rooftops or other structures in compliance with site assessment and schematics.',
    postedAt: new Date('2024-05-26'),
  },
];


export const mockApplications: Application[] = [
  {
    id: 'app-1',
    job: mockJobs[0],
    applicant: mockUser,
    status: 'Reviewed',
    appliedAt: new Date('2024-05-22'),
  },
  {
    id: 'app-2',
    job: mockJobs[4],
    applicant: mockUser,
    status: 'Applied',
    appliedAt: new Date('2024-05-21'),
  },
  {
    id: 'app-3',
    job: mockJobs[1],
    applicant: mockUser,
    status: 'Interviewing',
    appliedAt: new Date('2024-05-19'),
  },
    {
    id: 'app-4',
    job: mockJobs[6],
    applicant: mockUser,
    status: 'Shortlisted',
    appliedAt: new Date('2024-05-18'),
  },
   {
    id: 'app-5',
    job: mockJobs[2],
    applicant: mockUser,
    status: 'Rejected',
    appliedAt: new Date('2024-05-15'),
  }
];
